language: csharp
dist: trusty
os:
  - linux
  # - osx CoreCLR does not support OS X 10.9 (yet)
mono:
  - beta
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
env:
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
branches:
  only:
    - master
script:
  - ./build.sh --quiet verify
notifications:
  on_success: always
  on_failure: always
  on_start: always
