version: '1.0.{build}'
configuration:
- Debug
- Release
platform: Any CPU
environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
before_build:
- appveyor-retry dotnet restore -v Minimal
build_script:
- dotnet build "src\OnionArchitecture.Core.Domain" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
- dotnet build "src\OnionArchitecture.Core.DomainService" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
- dotnet build "src\OnionArchitecture.Core.ApplicationService" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
- dotnet build "src\OnionArchitecture.Infrastructure.Data" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
- dotnet build "src\OnionArchitecture.Infrastructure.Service" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
after_build:
- dotnet pack "src\OnionArchitecture.Core.Domain" -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts
- dotnet pack "src\OnionArchitecture.Core.DomainService" -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts
- dotnet pack "src\OnionArchitecture.Core.ApplicationService" -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts
- dotnet pack "src\OnionArchitecture.Infrastructure.Data" -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts
- dotnet pack "src\OnionArchitecture.Infrastructure.Service" -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts
artifacts:
- path: artifacts\**\*.*
cache:
- '%USERPROFILE%\.nuget\packages'