os: Visual Studio 2015
install:
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%

configuration: Release
branches:
  only:
    - master

before_build:
  - nuget restore OnionArchitecture.sln

build:
  project: OnionArchitecture.sln       
  verbosity: minimal