cache:
  - C:\Users\appveyor\AppData\Local\NuGet\Cache

# version format
version: 1.0.0.{build}

before_build:
  - nuget restore

notifications:

  # Slack
  - provider: Slack
    incoming_webhook:
      secure: https://hooks.slack.com/services/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
    channel: akoken